### ISSUE TITLE
Spooky fork?

### ISSUE THREAD

**Issue by prateekrastogi** [danlester/binderhub-voila-direct#1]
Hi,

I am facing troubles in running this repo in another identical github repo, if that repo is not directly forked from this repo. Consider these two repos:
https://github.com/paxos-raft/diagram
https://github.com/paxos-raft/binderhub-voila-direct

In the one in which i directly forked from your repo, I can launch the binder. But, in the other repo, not directly forked from your repo but bearing exactly the same code  your repo, I am unable to launch binder. 

Has your workaround been flagged by binder systems or are you aware any other problems?

**Comment by danlester** [comment]
Hello! I think you've removed your repos now, but let me know if you still have questions in the future.

Dan
